twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        app:
            version: '%app.version%'
            name: '%app.name%'
            theme: '%app.theme%'
            meta:
                title: '%env(APP_META_TITLE)%'
                description: '%env(APP_META_DESCRIPTION)%'
                keywords: '%env(APP_META_KEYWORDS)%'
when@test:
    twig:
        strict_variables: true
